apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: nexus

resources:
  - namespace.yaml
  - secrets.yaml
  - configmap.yaml
  - postgres.yaml
  - redis.yaml
  - minio.yaml
  - nexus-api.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  - hpa.yaml
  - pdb.yaml
  - network-policy.yaml
  - monitoring.yaml

commonLabels:
  app.kubernetes.io/name: nexus
  app.kubernetes.io/part-of: nexus-platform

images:
  - name: nexus/api
    newTag: latest
  - name: nexus/worker
    newTag: latest
